services:
  - type: web
    name: article-classifier-api-it
    env: python
    plan: free
    buildCommand: pip install -r requirements_api.txt
    startCommand: uvicorn api_app_it:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
